# permissions for end users to view expressapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expressapp-viewer-role
rules:
- apiGroups:
  - ibm.dev.ibm.dev
  resources:
  - expressapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.dev.ibm.dev
  resources:
  - expressapps/status
  verbs:
  - get
