# permissions for end users to edit expressapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expressapp-editor-role
rules:
- apiGroups:
  - ibm.dev.ibm.dev
  resources:
  - expressapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.dev.ibm.dev
  resources:
  - expressapps/status
  verbs:
  - get
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch